### PR TITLE
Support build cuda rocm

### PR DESCRIPTION
**Pull request by Cyberhan123**

### CODE REVIEW

**Comment by Cyberhan123** [comment]
https://github.com/saharNooby/rwkv.cpp/issues/151

**Comment by Cyberhan123** [comment]
@saharNooby hello If convenient, please merge this pull requests

**Review by saharNooby — APPROVED** [review]

**Comment by saharNooby** [comment]
```
 windows-latest-cmake (cuda12, -DRWKV_CUBLAS=ON)
succeeded ... in 21m 10s 
```

These are scary numbers. Mose of the time spent installing CUDA toolkit. I hope GitHub will not ban us for this.

**Comment by Cyberhan123** [comment]
wow，it fail with public

**Comment by Cyberhan123** [comment]
> ```
> windows-latest-cmake (cuda12, -DRWKV_CUBLAS=ON)
> succeeded ... in 21m 10s 
> ```
> 
> These are scary numbers. Mose of the time spent installing CUDA toolkit. I hope GitHub will not ban us for this.

No, we are using it correctly.

**Pull request merged**
